#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, os, signal, socket, subprocess, sys, tempfile, time, urllib.request
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def free_port()->int:
    with socket.socket() as s:
        s.bind(('127.0.0.1',0)); return int(s.getsockname()[1])

def wait(url:str, timeout:float=20.0)->tuple[int,str]:
    deadline=time.monotonic()+timeout; last=None
    while time.monotonic()<deadline:
        try:
            with urllib.request.urlopen(url,timeout=2) as response:
                return response.status,response.read().decode('utf-8','replace')
        except Exception as exc:
            last=exc; time.sleep(.1)
    raise RuntimeError(f'HTTP startup timeout for {url}: {last}')

def main()->int:
    ap=argparse.ArgumentParser(); ap.add_argument('--output',type=Path,default=ROOT/'evidence/r12_live_http_smoke.json'); a=ap.parse_args()
    failures=[]; evidence={}; port=free_port()
    with tempfile.TemporaryDirectory(prefix='cui-r12-http-') as td:
        data=Path(td)/'data'; data.mkdir(); cwd=Path(td)/'cwd'; cwd.mkdir(); log=Path(td)/'server.log'
        env=os.environ.copy(); env.update({'COMPANY_UI_ENVIRONMENT':'dev','COMPANY_UI_HOST':'127.0.0.1','COMPANY_UI_PORT':str(port),'COMPANY_UI_VISUALIZER_DATA_DIR':str(data),'PYTHONUNBUFFERED':'1'}); env.pop('COMPANY_UI_STORAGE_SECRET',None)
        handle=log.open('w',encoding='utf-8')
        proc=subprocess.Popen([sys.executable,str(ROOT/'app.py')],cwd=cwd,env=env,stdout=handle,stderr=subprocess.STDOUT,start_new_session=True)
        try:
            health,_=wait(f'http://127.0.0.1:{port}/healthz'); page_status,page=wait(f'http://127.0.0.1:{port}/visualizer')
            evidence.update({'health_status':health,'visualizer_status':page_status,'visualizer_contains_mount':'visualizer-editor-mount' in page or 'Visualizer' in page})
            secret_file=data/'.storage_secret'; evidence['secret_file']=secret_file.is_file()
            if not secret_file.is_file(): failures.append('local storage secret was not generated by exact app.py startup')
            else:
                secret=secret_file.read_text().strip(); evidence['secret_length']=len(secret)
                if len(secret)<32: failures.append('generated storage secret is shorter than 32 characters')
            if health>=400: failures.append(f'/healthz returned {health}')
            if page_status>=400: failures.append(f'/visualizer returned {page_status}')
            if not evidence['visualizer_contains_mount']: failures.append('/visualizer response did not contain expected Visualizer page content')
        except Exception as exc: failures.append(f'{type(exc).__name__}: {exc}')
        finally:
            if proc.poll() is None:
                proc.send_signal(signal.SIGTERM)
                try: proc.wait(timeout=12)
                except subprocess.TimeoutExpired: proc.kill(); proc.wait(timeout=5)
            handle.close(); evidence['returncode']=proc.returncode
            text=log.read_text(errors='replace'); evidence['server_log_tail']=text.splitlines()[-80:]
            if 'Traceback (most recent call last)' in text: failures.append('unexpected traceback in exact app.py server log')
            if proc.returncode not in (0,None): failures.append(f'exact app.py shutdown returned {proc.returncode}')
    result={'pass':not failures,'failures':failures,'evidence':evidence}; a.output.parent.mkdir(parents=True,exist_ok=True); a.output.write_text(json.dumps(result,indent=2)+'\n'); print(json.dumps({'pass':result['pass'],'failures':failures,'evidence':{k:v for k,v in evidence.items() if k!='server_log_tail'}},indent=2)); return 0 if result['pass'] else 1
if __name__=='__main__': raise SystemExit(main())
